#!/bin/bash
# Thanks Lubos Rendek - web@linuxconfig.org!

url="https://weather.com/weather/today/l"

download() {
    previous=$(find $HOME/.cache -maxdepth 0 -name "*_$1_sun")
    curl -s "$url/$1" > $2
    if [ -z $previous ] || [ $(diff $2 $previous) ];  then
        rm $previous 2> /dev/null
        sun_file=$2
    else
        rm $2
        sun_file=$previous
    fi
    echo "$sun_file"
}

get_times() {
    sun_times=$( cat $1 | sed 's/<span/\n/g' | sed 's/<\/span>/\n/g'  | grep -E "dp0-details-sunrise|dp0-details-sunset" | tr -d '\n' | sed 's/>/ /g' | cut -d " " -f 4,8 )
    sunrise=$(date --date="`echo $sun_times | awk '{ print $1}'` AM" +%R)
    sunset=$(date --date="`echo $sun_times | awk '{ print $2}'` PM" +%R)
    echo "🌄 $sunrise  🌇 $sunset"
}


main() {
    #obtain a location code from: https://weather.codes/search/
	LOCATION="USCA0830" # bay area
    #LOCATION="USMA0046" # for boston
    for i in "$@"; do
	case $i in
        -l|--location)
        LOCATION=$2
        shift
        shift
        ;;
        *)    
		;;
	esac
	done
    new_sun_file="$HOME/.cache/$(date '+%Y-%m-%d-%H:%M:%S')_"$LOCATION"_sun"
    sun_file=$(download $LOCATION $new_sun_file)
    get_times $sun_file
}
main "#@"
